# Generated by Django 2.2.4 on 2019-09-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_code', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('company_name', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default=0, max_length=50)),
                ('address_url', models.CharField(default=0, max_length=50)),
                ('chart_url', models.CharField(default=0, max_length=50)),
                ('feature', models.CharField(default=0, max_length=150)),
                ('related_bussiness', models.CharField(default=0, max_length=50)),
                ('tel', models.CharField(default=0, max_length=50)),
                ('class_name', models.CharField(default=0, max_length=20)),
                ('company_name_english', models.CharField(default=0, max_length=20)),
                ('represent_ceo', models.CharField(default=0, max_length=20)),
                ('built_date', models.CharField(default=0, max_length=20)),
                ('market_name', models.CharField(default=0, max_length=20)),
                ('on_market_date', models.CharField(default=0, max_length=20)),
                ('final_date', models.CharField(default=0, max_length=50)),
                ('unit_kabu', models.CharField(default=0, max_length=20)),
                ('employee_num', models.CharField(default=0, max_length=20)),
                ('employee_age', models.CharField(default=0, max_length=20)),
                ('employee_salary', models.CharField(default=0, max_length=20)),
                ('monitor_flag', models.IntegerField(default=0)),
                ('kabu_sum_number', models.IntegerField(default=0)),
            ],
        ),
    ]
