# Generated by Django 2.2.4 on 2019-09-08 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(default='', max_length=20)),
                ('year_sells', models.IntegerField(default=0)),
                ('year_profits', models.IntegerField(default=0)),
                ('year_eps', models.IntegerField(default=0)),
                ('company_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='front.Company')),
            ],
        ),
    ]
