# Generated by Django 2.2.4 on 2019-09-08 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_yeardata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yeardata',
            name='year_eps',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='yeardata',
            unique_together={('company_code', 'year')},
        ),
    ]
