# Generated by Django 2.2.4 on 2019-09-08 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_auto_20190908_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(max_length=20)),
                ('start_value', models.FloatField(max_length=20)),
                ('high_value', models.FloatField(max_length=20)),
                ('low_value', models.FloatField(max_length=20)),
                ('finish_value', models.FloatField(max_length=20)),
                ('amount', models.FloatField(max_length=20)),
                ('daily_per', models.FloatField(max_length=20)),
                ('company_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='front.Company')),
            ],
            options={
                'unique_together': {('company_code', 'day')},
            },
        ),
    ]
