# Generated by Django 2.2.4 on 2019-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_auto_20190909_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='kabu_sum_number',
            field=models.IntegerField(default=0),
        ),
    ]
