# Generated by Django 2.2.4 on 2019-10-06 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0007_dailydata_kabu_sum_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailydata',
            name='kabu_sum_number',
        ),
        migrations.AlterField(
            model_name='dailydata',
            name='daily_per',
            field=models.FloatField(default=0, max_length=20),
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle_day', models.DateField(max_length=20)),
                ('company_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='front.Company')),
            ],
            options={
                'unique_together': {('company_code', 'settle_day')},
            },
        ),
    ]
