# Generated by Django 2.2.4 on 2019-10-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0008_auto_20191006_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailydata',
            name='kabuyoho_signal',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
