# Generated by Django 2.2.7 on 2019-11-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0009_dailydata_kabuyoho_signal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address_url',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
