# Generated by Django 2.2.7 on 2020-05-24 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0010_auto_20191125_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanSlim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_earnings', models.CharField(default='', max_length=20)),
                ('annual_earnings', models.CharField(default='', max_length=20)),
                ('new_product_service_flg', models.CharField(default='', max_length=20)),
                ('supply_and_demand', models.CharField(default='', max_length=20)),
                ('leader_or_laggard', models.CharField(default='', max_length=20)),
                ('institutional_sponsorship', models.CharField(default='', max_length=20)),
                ('market', models.CharField(default='', max_length=20)),
                ('company_code', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='front.Company')),
            ],
        ),
    ]
