# Generated by Django 2.2.7 on 2020-08-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='wordMask',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('word', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
